/**
* Miru API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "ErrorResponse.h"
#include "Helpers.h"

namespace org::openapitools::server::model
{

nlohmann::json ErrorResponse::to_json() const
{
    nlohmann::json j;
    ::org::openapitools::server::model::to_json(j, *this);
    return j;
}

ErrorResponse ErrorResponse::from_json(const nlohmann::json& j)
{
    ErrorResponse o{};
    ::org::openapitools::server::model::from_json(j, o);
    return o;
}

void ErrorResponse::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool ErrorResponse::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool ErrorResponse::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "ErrorResponse" : pathPrefix;

        
    return success;
}

bool ErrorResponse::operator==(const ErrorResponse& other) const
{
    return
    
    error == other.error;
}

bool ErrorResponse::operator!=(const ErrorResponse& other) const
{
    return !(*this == other);
}

void to_json(nlohmann::json& j, const ErrorResponse& o)
{
    j = nlohmann::json::object();
    j["error"] = o.error;
    
}

void from_json(const nlohmann::json& j, ErrorResponse& o)
{
    j.at("error").get_to(o.error);
    
}

} // namespace org::openapitools::server::model

