/**
 * Miru API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the
 * class manually.
 */

#include "HashSchemaRequest.h"

#include "Helpers.h"

namespace org::openapitools::server::model {

nlohmann::json HashSchemaRequest::to_json() const {
  nlohmann::json j;
  ::org::openapitools::server::model::to_json(j, *this);
  return j;
}

HashSchemaRequest HashSchemaRequest::from_json(const nlohmann::json& j) {
  HashSchemaRequest o{};
  ::org::openapitools::server::model::from_json(j, o);
  return o;
}

void HashSchemaRequest::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw org::openapitools::server::helpers::ValidationException(msg.str());
  }
}

bool HashSchemaRequest::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool HashSchemaRequest::validate(std::stringstream& msg, const std::string& pathPrefix)
  const {
  bool success = true;
  const std::string _pathPrefix = pathPrefix.empty() ? "HashSchemaRequest" : pathPrefix;

  return success;
}

bool HashSchemaRequest::operator==(const HashSchemaRequest& other) const {
  return

    schema == other.schema;
}

bool HashSchemaRequest::operator!=(const HashSchemaRequest& other) const {
  return !(*this == other);
}

void to_json(nlohmann::json& j, const HashSchemaRequest& o) {
  j = nlohmann::json::object();
  j["schema"] = o.schema;
}

void from_json(const nlohmann::json& j, HashSchemaRequest& o) {
  j.at("schema").get_to(o.schema);
}

}  // namespace org::openapitools::server::model
