/**
* Miru API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "HashSerializedConfigSchemaFormat.h"
#include "Helpers.h"

namespace org::openapitools::server::model
{

nlohmann::json HashSerializedConfigSchemaFormat::to_json() const
{
    nlohmann::json j;
    ::org::openapitools::server::model::to_json(j, *this);
    return j;
}

HashSerializedConfigSchemaFormat HashSerializedConfigSchemaFormat::from_json(const nlohmann::json& j)
{
    HashSerializedConfigSchemaFormat o{};
    ::org::openapitools::server::model::from_json(j, o);
    return o;
}

void HashSerializedConfigSchemaFormat::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool HashSerializedConfigSchemaFormat::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool HashSerializedConfigSchemaFormat::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "HashSerializedConfigSchemaFormat" : pathPrefix;

    
    if (value == HashSerializedConfigSchemaFormat::eHashSerializedConfigSchemaFormat::INVALID_VALUE_OPENAPI_GENERATED)
    {
        success = false;
        msg << _pathPrefix << ": has no value;";
    }

    return success;
}

bool HashSerializedConfigSchemaFormat::operator==(const HashSerializedConfigSchemaFormat& other) const
{
    return
    value == other.value
    ;
}

bool HashSerializedConfigSchemaFormat::operator!=(const HashSerializedConfigSchemaFormat& other) const
{
    return !(*this == other);
}

void to_json(nlohmann::json& j, const HashSerializedConfigSchemaFormat& o)
{
    j = nlohmann::json::object();
    
    switch (o.value)
    {
    case HashSerializedConfigSchemaFormat::eHashSerializedConfigSchemaFormat::INVALID_VALUE_OPENAPI_GENERATED:
        j = "INVALID_VALUE_OPENAPI_GENERATED";
        break;
    case HashSerializedConfigSchemaFormat::eHashSerializedConfigSchemaFormat::HASH_SERIALIZED_CONFIG_SCHEMA_FORMAT_JSON:
        j = "json";
        break;
    case HashSerializedConfigSchemaFormat::eHashSerializedConfigSchemaFormat::HASH_SERIALIZED_CONFIG_SCHEMA_FORMAT_YAML:
        j = "yaml";
        break;
    }
}

void from_json(const nlohmann::json& j, HashSerializedConfigSchemaFormat& o)
{
    
    auto s = j.get<std::string>();
    if(s == "json") {
        o.value = HashSerializedConfigSchemaFormat::eHashSerializedConfigSchemaFormat::HASH_SERIALIZED_CONFIG_SCHEMA_FORMAT_JSON;
    } 
    else if(s == "yaml") {
        o.value = HashSerializedConfigSchemaFormat::eHashSerializedConfigSchemaFormat::HASH_SERIALIZED_CONFIG_SCHEMA_FORMAT_YAML;
    }  else {
        std::stringstream ss;
        ss << "Unexpected value " << s << " in json"
           << " cannot be converted to enum of type"
           << " HashSerializedConfigSchemaFormat::eHashSerializedConfigSchemaFormat";
        throw std::invalid_argument(ss.str());
    } 
    
}

} // namespace org::openapitools::server::model

