/**
 * Miru API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the
 * class manually.
 */

#include "RefreshLatestConcreteConfigRequest.h"

#include "Helpers.h"

namespace org::openapitools::server::model {

nlohmann::json RefreshLatestConcreteConfigRequest::to_json() const {
  nlohmann::json j;
  ::org::openapitools::server::model::to_json(j, *this);
  return j;
}

RefreshLatestConcreteConfigRequest RefreshLatestConcreteConfigRequest::from_json(
  const nlohmann::json& j) {
  RefreshLatestConcreteConfigRequest o{};
  ::org::openapitools::server::model::from_json(j, o);
  return o;
}

void RefreshLatestConcreteConfigRequest::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw org::openapitools::server::helpers::ValidationException(msg.str());
  }
}

bool RefreshLatestConcreteConfigRequest::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool RefreshLatestConcreteConfigRequest::validate(
  std::stringstream& msg,
  const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
    pathPrefix.empty() ? "RefreshLatestConcreteConfigRequest" : pathPrefix;

  return success;
}

bool RefreshLatestConcreteConfigRequest::operator==(
  const RefreshLatestConcreteConfigRequest& other) const {
  return

    config_schema_digest == other.config_schema_digest &&
    config_slug == other.config_slug;
}

bool RefreshLatestConcreteConfigRequest::operator!=(
  const RefreshLatestConcreteConfigRequest& other) const {
  return !(*this == other);
}

void to_json(nlohmann::json& j, const RefreshLatestConcreteConfigRequest& o) {
  j = nlohmann::json::object();
  j["config_schema_digest"] = o.config_schema_digest;
  j["config_slug"] = o.config_slug;
}

void from_json(const nlohmann::json& j, RefreshLatestConcreteConfigRequest& o) {
  j.at("config_schema_digest").get_to(o.config_schema_digest);
  j.at("config_slug").get_to(o.config_slug);
}

}  // namespace org::openapitools::server::model
