/**
* Miru API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ErrorResponse.h
 *
 * 
 */

#ifndef ErrorResponse_H_
#define ErrorResponse_H_


#include "Error.h"
#include <nlohmann/json.hpp>
#include <optional>

namespace org::openapitools::server::model
{

struct  ErrorResponse
{
    

    org::openapitools::server::model::Error error;
    

    bool operator==(const ErrorResponse& other) const;
    bool operator!=(const ErrorResponse& other) const;

    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    nlohmann::json to_json() const;
    static ErrorResponse from_json(const nlohmann::json& j);
};

 void to_json(nlohmann::json& j, const ErrorResponse& o);
 void from_json(const nlohmann::json& j, ErrorResponse& o);


} // namespace org::openapitools::server::model


#endif /* ErrorResponse_H_ */
