/**
* Miru API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * HashSerializedConfigSchemaFormat.h
 *
 * 
 */

#ifndef HashSerializedConfigSchemaFormat_H_
#define HashSerializedConfigSchemaFormat_H_


#include <nlohmann/json.hpp>
#include <optional>

namespace org::openapitools::server::model
{

struct  HashSerializedConfigSchemaFormat
{
    
    enum eHashSerializedConfigSchemaFormat {
        // To have a valid default value.
        // Avoiding name clashes with user defined
        // enum values
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        HASH_SERIALIZED_CONFIG_SCHEMA_FORMAT_JSON, 
        HASH_SERIALIZED_CONFIG_SCHEMA_FORMAT_YAML
    };

    HashSerializedConfigSchemaFormat::eHashSerializedConfigSchemaFormat value = HashSerializedConfigSchemaFormat::eHashSerializedConfigSchemaFormat::INVALID_VALUE_OPENAPI_GENERATED;

    bool operator==(const HashSerializedConfigSchemaFormat& other) const;
    bool operator!=(const HashSerializedConfigSchemaFormat& other) const;

    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    nlohmann::json to_json() const;
    static HashSerializedConfigSchemaFormat from_json(const nlohmann::json& j);
};

 void to_json(nlohmann::json& j, const HashSerializedConfigSchemaFormat& o);
 void from_json(const nlohmann::json& j, HashSerializedConfigSchemaFormat& o);


} // namespace org::openapitools::server::model


#endif /* HashSerializedConfigSchemaFormat_H_ */
