/**
* Miru API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "BaseConfigInstance.h"
#include "Helpers.h"

namespace org::openapitools::server::model
{

nlohmann::json BaseConfigInstance::to_json() const
{
    nlohmann::json j;
    ::org::openapitools::server::model::to_json(j, *this);
    return j;
}

BaseConfigInstance BaseConfigInstance::from_json(const nlohmann::json& j)
{
    BaseConfigInstance o{};
    ::org::openapitools::server::model::from_json(j, o);
    return o;
}

void BaseConfigInstance::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool BaseConfigInstance::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool BaseConfigInstance::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "BaseConfigInstance" : pathPrefix;

                            
    return success;
}

bool BaseConfigInstance::operator==(const BaseConfigInstance& other) const
{
    return
    
    object == other.object && id == other.id && created_at == other.created_at && device_id == other.device_id && config_schema_id == other.config_schema_id && config_instance == other.config_instance;
}

bool BaseConfigInstance::operator!=(const BaseConfigInstance& other) const
{
    return !(*this == other);
}

void to_json(nlohmann::json& j, const BaseConfigInstance& o)
{
    j = nlohmann::json::object();
    j["object"] = o.object;
    j["id"] = o.id;
    j["created_at"] = o.created_at;
    j["device_id"] = o.device_id;
    j["config_schema_id"] = o.config_schema_id;
    if (o.config_instance.has_value()) {
        j["config_instance"] = o.config_instance.value();
    } else {
        j["config_instance"] = nullptr;
    }
    
}

void from_json(const nlohmann::json& j, BaseConfigInstance& o)
{
    j.at("object").get_to(o.object);
    j.at("id").get_to(o.id);
    j.at("created_at").get_to(o.created_at);
    j.at("device_id").get_to(o.device_id);
    j.at("config_schema_id").get_to(o.config_schema_id);
    if (j.find("config_instance") != j.end()) {
        if (j.at("config_instance").is_null()) {
            o.config_instance = std::nullopt;
        } else {
            o.config_instance = j.at("config_instance").get<nlohmann::json>();
        }
    }
    
}

} // namespace org::openapitools::server::model

