/**
* Miru API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "BaseConcreteConfig.h"
#include "Helpers.h"

namespace org::openapitools::server::model
{

nlohmann::json BaseConcreteConfig::to_json() const
{
    nlohmann::json j;
    ::org::openapitools::server::model::to_json(j, *this);
    return j;
}

BaseConcreteConfig BaseConcreteConfig::from_json(const nlohmann::json& j)
{
    BaseConcreteConfig o{};
    ::org::openapitools::server::model::from_json(j, o);
    return o;
}

void BaseConcreteConfig::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool BaseConcreteConfig::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool BaseConcreteConfig::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "BaseConcreteConfig" : pathPrefix;

                            
    return success;
}

bool BaseConcreteConfig::operator==(const BaseConcreteConfig& other) const
{
    return
    
    object == other.object && id == other.id && created_at == other.created_at && client_id == other.client_id && config_schema_id == other.config_schema_id && concrete_config == other.concrete_config;
}

bool BaseConcreteConfig::operator!=(const BaseConcreteConfig& other) const
{
    return !(*this == other);
}

void to_json(nlohmann::json& j, const BaseConcreteConfig& o)
{
    j = nlohmann::json::object();
    j["object"] = o.object;
    j["id"] = o.id;
    j["created_at"] = o.created_at;
    j["client_id"] = o.client_id;
    j["config_schema_id"] = o.config_schema_id;
    if (o.concrete_config.has_value()) {
        j["concrete_config"] = o.concrete_config.value();
    } else {
        j["concrete_config"] = nullptr;
    }
    
}

void from_json(const nlohmann::json& j, BaseConcreteConfig& o)
{
    j.at("object").get_to(o.object);
    j.at("id").get_to(o.id);
    j.at("created_at").get_to(o.created_at);
    j.at("client_id").get_to(o.client_id);
    j.at("config_schema_id").get_to(o.config_schema_id);
    if (j.find("concrete_config") != j.end()) {
        if (j.at("concrete_config").is_null()) {
            o.concrete_config = std::nullopt;
        } else {
            o.concrete_config = j.at("concrete_config").get<nlohmann::json>();
        }
    }
    
}

} // namespace org::openapitools::server::model

