/**
* Miru API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ConfigInstance.h
 *
 * 
 */

#ifndef ConfigInstance_H_
#define ConfigInstance_H_


#include "ConfigInstanceStatus.h"
#include <nlohmann/json.hpp>
#include "ConfigInstanceTargetStatus.h"
#include "ConfigInstanceErrorStatus.h"
#include "ConfigInstanceActivityStatus.h"
#include <string>
#include <nlohmann/json.hpp>
#include <optional>

namespace org::openapitools::server::model
{

struct  ConfigInstance
{
    

    std::string object;
    std::string id;
    org::openapitools::server::model::ConfigInstanceTargetStatus target_status;
    org::openapitools::server::model::ConfigInstanceStatus status;
    org::openapitools::server::model::ConfigInstanceActivityStatus activity_status;
    org::openapitools::server::model::ConfigInstanceErrorStatus error_status;
    std::optional<std::string> relative_filepath;
    std::string created_at;
    std::string updated_at;
    std::string config_schema_id;
    std::string config_type_id;
    nlohmann::json content;
    

    bool operator==(const ConfigInstance& other) const;
    bool operator!=(const ConfigInstance& other) const;

    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    nlohmann::json to_json() const;
    static ConfigInstance from_json(const nlohmann::json& j);
};

 void to_json(nlohmann::json& j, const ConfigInstance& o);
 void from_json(const nlohmann::json& j, ConfigInstance& o);


} // namespace org::openapitools::server::model


#endif /* ConfigInstance_H_ */
