/**
* Miru API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ConfigInstanceActivityStatus.h
 *
 * Last known activity state of the config instance
 */

#ifndef ConfigInstanceActivityStatus_H_
#define ConfigInstanceActivityStatus_H_


#include <nlohmann/json.hpp>
#include <optional>

namespace org::openapitools::server::model
{

struct  ConfigInstanceActivityStatus
{
    
    enum eConfigInstanceActivityStatus {
        // To have a valid default value.
        // Avoiding name clashes with user defined
        // enum values
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        CONFIG_INSTANCE_ACTIVITY_STATUS_CREATED, 
        CONFIG_INSTANCE_ACTIVITY_STATUS_VALIDATING, 
        CONFIG_INSTANCE_ACTIVITY_STATUS_VALIDATED, 
        CONFIG_INSTANCE_ACTIVITY_STATUS_QUEUED, 
        CONFIG_INSTANCE_ACTIVITY_STATUS_DEPLOYED, 
        CONFIG_INSTANCE_ACTIVITY_STATUS_REMOVED
    };

    ConfigInstanceActivityStatus::eConfigInstanceActivityStatus value = ConfigInstanceActivityStatus::eConfigInstanceActivityStatus::INVALID_VALUE_OPENAPI_GENERATED;

    bool operator==(const ConfigInstanceActivityStatus& other) const;
    bool operator!=(const ConfigInstanceActivityStatus& other) const;

    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    nlohmann::json to_json() const;
    static ConfigInstanceActivityStatus from_json(const nlohmann::json& j);
};

 void to_json(nlohmann::json& j, const ConfigInstanceActivityStatus& o);
 void from_json(const nlohmann::json& j, ConfigInstanceActivityStatus& o);


} // namespace org::openapitools::server::model


#endif /* ConfigInstanceActivityStatus_H_ */
