/**
* Miru API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ConfigInstanceTargetStatus.h
 *
 * 
 */

#ifndef ConfigInstanceTargetStatus_H_
#define ConfigInstanceTargetStatus_H_


#include <nlohmann/json.hpp>
#include <optional>

namespace org::openapitools::server::model
{

struct  ConfigInstanceTargetStatus
{
    
    enum eConfigInstanceTargetStatus {
        // To have a valid default value.
        // Avoiding name clashes with user defined
        // enum values
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        CONFIG_INSTANCE_TARGET_STATUS_CREATED, 
        CONFIG_INSTANCE_TARGET_STATUS_DEPLOYED, 
        CONFIG_INSTANCE_TARGET_STATUS_REMOVED
    };

    ConfigInstanceTargetStatus::eConfigInstanceTargetStatus value = ConfigInstanceTargetStatus::eConfigInstanceTargetStatus::INVALID_VALUE_OPENAPI_GENERATED;

    bool operator==(const ConfigInstanceTargetStatus& other) const;
    bool operator!=(const ConfigInstanceTargetStatus& other) const;

    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    nlohmann::json to_json() const;
    static ConfigInstanceTargetStatus from_json(const nlohmann::json& j);
};

 void to_json(nlohmann::json& j, const ConfigInstanceTargetStatus& o);
 void from_json(const nlohmann::json& j, ConfigInstanceTargetStatus& o);


} // namespace org::openapitools::server::model


#endif /* ConfigInstanceTargetStatus_H_ */
